"""initial

Revision ID: 109dc3a13c29
Revises: 
Create Date: 2026-02-13 08:17:00.014363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109dc3a13c29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "events",

        sa.Column("EventID", sa.Integer, primary_key=True, index=True),

        # sa.Column("VenueID", sa.Integer, sa.ForeignKey("venues.VenueID"), nullable=False)
        # sa.Column("CategoryID", sa.Integer, sa.ForeignKey("categories.CategoryID"), nullable=True)
        # sa.Column("TimeID", sa.Integer, sa.ForeignKey("times.TimeID"), nullable=True)
        
        sa.Column("VenueID", sa.Integer, nullable=False),
        sa.Column("CategoryID", sa.Integer, nullable=True),
        sa.Column("TimeID", sa.Integer, nullable=True),

        sa.Column("Name", sa.String(length=200), nullable=False),
        sa.Column("StartDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("EndDate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("Desc", sa.Text(), nullable=True),

        sa.Column("ImagePoster", sa.String(length=500), nullable=True),

        sa.Column("TicketPrice", sa.Numeric(10, 2), nullable=True),

        sa.Column(
            "PublicityLevel",
            sa.Enum("Public", "Private", "Unlisted", name="publicity_levels"),
            nullable=False,
            server_default="Public",
        ),

        sa.Column("Approved", sa.Boolean(), nullable=False, server_default=sa.text("0")),
    )
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
