"""events

Revision ID: d99f31c89d96
Revises: 24f980f1a84f
Create Date: 2026-02-13 09:56:50.834495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99f31c89d96'
down_revision: Union[str, Sequence[str], None] = '24f980f1a84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    op.drop_table('TimeSlots')
    op.drop_table('users')
    op.drop_table('Notifications')
    op.drop_table('SeatTypes')
    op.drop_table('Venues')
    op.drop_table('Bookings')
    op.drop_table('Category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('CategoryID', sa.INTEGER(), nullable=True),
    sa.Column('Name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('CategoryID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Bookings',
    sa.Column('BookingID', sa.INTEGER(), nullable=True),
    sa.Column('EventID', sa.INTEGER(), nullable=False),
    sa.Column('TimeID', sa.INTEGER(), nullable=False),
    sa.Column('BookerID', sa.INTEGER(), nullable=False),
    sa.Column('Status', sa.TEXT(), server_default=sa.text("'Pending'"), nullable=True),
    sa.CheckConstraint("Status IN ('Pending','Confirmed','Cancelled')"),
    sa.ForeignKeyConstraint(['BookerID'], ['Users.UserID'], ),
    sa.ForeignKeyConstraint(['EventID'], ['Events.EventID'], ),
    sa.ForeignKeyConstraint(['TimeID'], ['TimeSlots.TimeID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    op.create_table('Venues',
    sa.Column('VenueID', sa.INTEGER(), nullable=True),
    sa.Column('VenueName', sa.TEXT(), nullable=False),
    sa.Column('Location', sa.TEXT(), nullable=False),
    sa.Column('Reviews', sa.TEXT(), nullable=True),
    sa.Column('SeatingCapacity', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('VenueID')
    )
    op.create_table('SeatTypes',
    sa.Column('SeatID', sa.INTEGER(), nullable=True),
    sa.Column('SeatType', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('SeatID'),
    sa.UniqueConstraint('SeatType')
    )
    op.create_table('Notifications',
    sa.Column('NotificationID', sa.INTEGER(), nullable=True),
    sa.Column('UserID', sa.INTEGER(), nullable=False),
    sa.Column('Message', sa.TEXT(), nullable=False),
    sa.Column('IsRead', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint('IsRead IN (0,1)'),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('NotificationID')
    )
    op.create_table('users',
    sa.Column('UserID', sa.INTEGER(), nullable=True),
    sa.Column('Role', sa.TEXT(), server_default=sa.text("'User'"), nullable=False),
    sa.Column('Email', sa.TEXT(), nullable=False),
    sa.Column('Password', sa.TEXT(), nullable=False),
    sa.Column('Phone', sa.TEXT(), nullable=True),
    sa.Column('Status', sa.TEXT(), server_default=sa.text("'Active'"), nullable=False),
    sa.CheckConstraint("Role IN ('Venue','User','Admin')"),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('TimeSlots',
    sa.Column('TimeID', sa.INTEGER(), nullable=True),
    sa.Column('StartTime', sa.TEXT(), nullable=False),
    sa.Column('EndTime', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('TimeID')
    )
    op.create_table('Events',
    sa.Column('EventID', sa.INTEGER(), nullable=True),
    sa.Column('VenueID', sa.INTEGER(), nullable=False),
    sa.Column('CategoryID', sa.INTEGER(), nullable=False),
    sa.Column('TimeID', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.TEXT(), nullable=False),
    sa.Column('StartDate', sa.TEXT(), nullable=False),
    sa.Column('EndDate', sa.TEXT(), nullable=False),
    sa.Column('Description', sa.TEXT(), nullable=True),
    sa.Column('ImageURL', sa.TEXT(), nullable=True),
    sa.Column('TicketPrice', sa.REAL(), nullable=True),
    sa.Column('PublicityLevel', sa.TEXT(), server_default=sa.text("'Public'"), nullable=True),
    sa.Column('Approved', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint("PublicityLevel IN ('Public','Private','Unlisted')"),
    sa.CheckConstraint('Approved IN (0,1)'),
    sa.ForeignKeyConstraint(['CategoryID'], ['Category.CategoryID'], ),
    sa.ForeignKeyConstraint(['TimeID'], ['TimeSlots.TimeID'], ),
    sa.ForeignKeyConstraint(['VenueID'], ['Venues.VenueID'], ),
    sa.PrimaryKeyConstraint('EventID')
    )
    # ### end Alembic commands ###
